app:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    pool-size: 30
    validationQuery: SELECT 1
  data:
    mongo:
      database:
        port: 27017
        uri: mongodb://Billy08:admin@cluster0-shard-00-00.d5dcl.mongodb.net:27017,cluster0-shard-00-01.d5dcl.mongodb.net:27017,cluster0-shard-00-02.d5dcl.mongodb.net:27017/?ssl=true&replicaSet=atlas-umcyfe-shard-0&authSource=admin&retryWrites=true&w=majority
