app:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    pool-size: 30
    validationQuery: SELECT 1
  data:
    mongo:
      host: localhost
      port: 27017
      database: demo
